#!/usr/bin/env python3
"""
RETIRED — the Aurora Glass theme (sl-nav.css v2) uses the operating
system's native font stack, so no UI webfonts are embedded anymore.
This script and the .ttf files in fonts/ui/ are kept only for the
record; running it will find no UI-FONTS marker in sl-nav.css and
exit without changing anything.

(Historical purpose: base64-embed every TTF in _shared/fonts/ui/ as
@font-face rules spliced into the top of sl-nav.css.)
"""
from __future__ import annotations
import base64
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
UI_DIR = ROOT / "_shared" / "fonts" / "ui"
NAV_CSS = ROOT / "_shared" / "sl-nav.css"

# (filename in fonts/ui/, font-family, font-weight)
FONTS = [
    ("Audiowide.ttf",     "Audiowide",        400),
    ("Orbitron-500.ttf",  "Orbitron",         500),
    ("Orbitron-700.ttf",  "Orbitron",         700),
    ("Orbitron-900.ttf",  "Orbitron",         900),
    ("ShareTechMono.ttf", "Share Tech Mono",  400),
    ("VT323.ttf",         "VT323",            400),
]

BEGIN = "/* UI-FONTS:BEGIN — base64-embedded UI fonts (Audiowide, Orbitron, Share Tech Mono, VT323). Generated by _shared/fonts/_build_ui_fonts.py from the .ttf files in _shared/fonts/ui/. */"
END   = "/* UI-FONTS:END */"

GOOGLE_IMPORT_LINE = "@import url('https://fonts.googleapis.com/css2?family=Audiowide&family=Orbitron:wght@500;700;900&family=Share+Tech+Mono&family=VT323&display=swap');"


def build_block() -> str:
    rules = [BEGIN]
    for fname, family, weight in FONTS:
        path = UI_DIR / fname
        if not path.exists():
            print(f"  ERROR: missing font {path}", file=sys.stderr)
            sys.exit(1)
        b64 = base64.b64encode(path.read_bytes()).decode("ascii")
        rules.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url(data:font/ttf;base64,{b64}) format('truetype');\n"
            "}"
        )
    rules.append(END)
    return "\n".join(rules)


def main() -> int:
    block = build_block()
    css = NAV_CSS.read_text(encoding="utf-8")

    # Idempotent: replace existing UI-FONTS block, or replace the
    # Google Fonts @import on first run.
    pattern = re.compile(
        re.escape(BEGIN) + r"[\s\S]*?" + re.escape(END), re.DOTALL
    )
    if pattern.search(css):
        new_css = pattern.sub(lambda _m: block, css)
        action = "refreshed"
    elif GOOGLE_IMPORT_LINE in css:
        new_css = css.replace(GOOGLE_IMPORT_LINE, block)
        action = "spliced"
    else:
        print("  WARN: neither UI-FONTS block nor Google Fonts @import "
              "found in sl-nav.css; nothing to do.", file=sys.stderr)
        return 1

    NAV_CSS.write_text(new_css, encoding="utf-8")
    delta = len(new_css) - len(css)
    print(f"  {action}: UI fonts block in sl-nav.css "
          f"({delta:+,} bytes; {len(FONTS)} font faces)")
    print("  Now run _shared/sync_inline.py to push the updated CSS "
          "into every tool.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
